name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.ENVKEY_POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.ENVKEY_POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.ENVKEY_POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.ENVKEY_DATABASE_URL}}
          file_name: ".env.test"
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app npm run test